### ISSUE TITLE
Mention using `--rate-limit` option when writing csv files with `influx write`

### ISSUE THREAD

**Issue by philjb** [influxdata/book.github.io#13]
I’d like to suggest that the `--rate-limit` option be mentioned in this section on csv uploading: https://awesome.influxdata.com/docs/part-3/writing-and-querying-data/#writing-raw-csv-data

For all but the smallest csv files, uploading one is likely to run into write rate limits. I'm suggesting always using `--rate-limit` with `influx write` to stay under the limits.

**Comment by Anaisdg** [comment]
Thank you!
