### ISSUE TITLE
slightly garbled Time-to-Awesome "Input Format vs Output Format" intro

### ISSUE THREAD

**Issue by rnav1234** [influxdata/book.github.io#30]
Folks,
The very first paragraph on: https://awesome.influxdata.com/docs/part-2/input-format-vs-output-format/  is partially garbled. See sentence 5 within: 

`The InfluxDB input format is line protocol. The InfluxDB output format is Annotated CSV. The input format is different from the InfluxDB persistence. The Annotated CSV output can match the InfluxDB persistence format with simple Flux queries. However, can add Flux transformations to your query such that the Annotated CSV output doesn’t reflect the InfluxDB persistence format. Understanding these subtle differences is critical for good schema design and for using InfluxDB optimally.`

In essence the final sentence tells me to worry about a concept remaining unexplained in the preceding sentences :-|

Also as a new InfluxDB cloud user I do not currently understand "InfluxDB persistence format". Is this still important for InfluxDB cloud users? Else rewriting of this section to help readers pay extra attention to critical subtleties is appreciated :-)

**Comment by rickspencer3** [comment]
Could you take a look at the proposed change and see if it improves readability? Also, feel free to make a PR for your own change as well.

**Comment by rickspencer3** [comment]
I'm to go ahead and merge the PR and close this ticket. Please reopen this issue or make another PR if needed. Thank you again.
